### ISSUE TITLE
Structure creation coordination in atomrdf is dfiiferent from pyiron 

### ISSUE THREAD

**Issue by sepidbgh** [pyscal/pyscal3#45]
If you want to create your previously pyrion written workflow in atomrdf, specifically if you have some shifting regarding atoms positions, you need to write your workflow again in atomrdf coordination. 

element='Mg'
repetitions=[2,2,2]
a=3.187
covera= np.sqrt(8/3)
crystalstructure='hcp'

Pyiron: 
n_atoms= 16 	
**cell= [[6.374, 0.0, 0.0], [-3.187, 5.520045923722011, 0.0], [0.0, 0.0, 10.40869841366665]]** 	
cell.cellpar = [6.374, 6.374, 10.40869841366665, 90.0, 90.0, 120.00000000000001]

atomrdf:
n_atoms= 16 	
**cell= [[3.187, -5.519883999999999, 0.0], [3.187, 5.519883999999999, 0.0], [0.0, 0.0, 10.40869841366665]]**
cell.cellpar = [6.373859770457457, 6.373859770457457, 10.40869841366665, 90.0, 90.0, 119.99854443834525

**Comment by srmnitc** [comment]
@sepidbgh for reporting. Fixed in v 3.2.6. The new version will be available on conda/pip in few hours. dhcp has also been changed accordingly.
